- label: "Setup"
  message: "Completed"
  color: "green"
  - label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 500"
  - message: "$payload.pull_request.user.login"
  color: "purple"